### ISSUE TITLE
Known compounds on which this tool worked on

### ISSUE THREAD

**Issue by smruti241** [zealseeker/admetsar2-doc#1]
Hi,
Actually I want to understand how this ADMETSar works? I have gone through the papers but didnt understand properly. What are the known compounds or datasets you have worked? Can you give me some links or data regarding the inputs? How can we use those inputs for our research? Please let me know the whole scenario.
Thank you

**Comment by zealseeker** [comment]
Hi,
I think this page https://zealseeker.github.io/admetsar2-doc/ gives the details of the datasets and sources you want. The description of how the models were build is already described in the paper 
> Hongbin Yang, Chaofeng Lou, Lixia Sun, Jie Li, Yingchun Cai, Zhuang Wang, Weihua Li, Guixia Liu, Yun Tang. admetSAR 2.0: web-service for prediction and optimization of chemical ADMET properties. Bioinformatics, 2018, bty707.
https://doi.org/10.1093/bioinformatics/bty707

As for how you can use the dataset, it may depend on what kind of research you want to do.

**Comment by smruti241** [comment]
Okay Thank you so much for the information
